// class RelaxTourText {
//   static String text = 'Privacy Policy for Android Apps\n\n1. Purpose of Processing Personal Information.\n\nApps prepared by this developer handle personal information for the following purposes and are not used for any purpose other than:\n\n1) Using the free app for delegation of authority required by the AdMob Advertising Library (Google Play Library)\n\n2. Consignment of Personal Information\nApps created by this developer do not entrust personal information to other companies. \n\n3. Rights and Obligations of the Data Subject and How to Exercise Them \nAs a personal information subject, users can exercise their right to privacy at any time. \nHowever, this app does not collect and retain usage information of app users.\nUse only for app functions. \n\n4. Creating Items of Personal Information to be Processed\nThe following personal information items will be processed.\nandroid.permission.INTERNET: Used for AdMob advertisement and Youtube videos.\nandroid.permissionACCESS_NETWORK_STATE: Used to confirm the use of mobile networks and AdMob advertising.\nandroid.permission.FOREGROUND_SERVICE: Used for media background playback.\ncom.android.vending.BILLING: Used for In-App Billing\n\n5. Destruction of Personal Information\nWe do not collect and retain user usage information of app users. Therefore, we do not have any personal information that needs to be destroyed.\n\n6. Securing Safety of Personal Information\nWe do not collect and retain user usage information of app users.';
// }

class RelaxTourText {
  static String text = 'Privacy Policy\n\nAndroid App Privacy Policy\n\n1. Purpose of processing personal information. The app created by this developer processes personal information for the following purposes and is not used for any other purpose than the following purposes.\n\n1) For paid members only, the app uses it to identify community users\n\n2. Whether to entrust personal information processing\nThis developers app does not entrust personal information processing to other companies.\n\n3. Rights and obligations of the information subject and the method of exercising them\nUsers can exercise their rights related to personal information protection at any time as a personal information subject.\nHowever, developers do not collect and retain user usage information in this app. Use only for application functionality.\n\n4. Preparation of items of personal information to be processed\nThe following privacy items are being processed:\n\nandroid.permission.INTERNET: Download soundtrack. It is used to identify paid members and free members.\nandroid.permission.FOREGROUND_SERVICE: Used to play sound in the background.\nandroid.permission.ACCESS_NETWORK_STATE: : This is used to verify the availability of mobile networks for the above privileges.\nandroid.permission.WRITE_EXTERNAL_STORAGE: Used only for storing soundtracks on devices.\n\n5. Destruction of personal information\nIt is used only to identify subscription information of paid members and is discarded at the same time as cancellation of subscription.\n\n6. Measures to secure the safety of personal information\nWe never use the app users usage information for negative purposes.';
}

class NhaText {
  static String text = '안드로이드앱 개인정보취급방침\n\n1. 개인정보의 처리 목적. 본 개발자가 작성한 앱은(는) 다음의 목적을 위하여 개인정보를 처리하고 있으며, 다음의 목적 이외의 용도로는 이용하지 않습니다.\n\n1) 무료 앱에서 Admob 광고 라이브러리(Google Play Lib)가 필요로 하는 권한 위임을 위해 사용\n\n2. 개인정보처리 위탁 여부\n본 개발자의 앱은 타 업체에 개인정보처리를 위탁하지 않습니다.\n\n3. 정보주체의 권리,의무 및 그 행사방법\n이용자는 개인정보주체로서 언제든지 개인정보 보호 관련 권리를 행사할 수 있습니다.\n다만, 본 앱은 앱 사용자의 사용정보를 수집 및 보유하지 않습니다. 앱 기능에 활용에만 사용합니다.\n\n4. 처리하는 개인정보의 항목 작성\n다음의 개인정보 항목을 처리하고 있습니다.\n\nandroid.permission.INTERNET: Admob 광고와 Youtube 영상 재생을 위해 사용합니다.\nandroid.permission.ACCESS_NETWORK_STATE: : Admob 광고를 위해, 모바일 네트워크 사용 유무 확인을 위해 사용합니다.\n\n5. 개인정보의 파기\n앱 사용자의 사용정보를 수집 및 보유하지 않습니다. 따라서 파기해야하는 개인정보를 가지고 있지 않습니다.\n\n6. 개인정보의 안전성 확보 조치\n앱 사용자의 사용정보를 수집 및 보유하지 않습니다.';
}

class CueTalkText {
  static String text = '큐톡 소개 내용';
}